---
dockerhub_username: your-dockerhub-username
dockerhub_password: your-dockerhub-access-token

web_app_name: devops-app
web_app_docker_image: "{{ dockerhub_username }}/devops-info-service"
web_app_docker_tag: latest
web_app_port: 8000
web_app_internal_port: 8000

